---
# Project Variables
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: alpine
buildImageVersion: latest

finalImageName: pandoc
finalImageVersion: 2.7
appName: PanDoc
